### ISSUE TITLE
How to change the fixed width?

### ISSUE THREAD

**Issue by danicarla** [PhilippeMarcMeyer/vanillaSelectBox#33]
Hi

I need change the width in multiselect checkboxes.. 
But, i have different sizes on my site... is there a way to allow to do this directly in the select?

Ex. 
`<select name="example[]" multiple size="2" style="width:250px;">`

**Comment by PhilippeMarcMeyer** [comment]
Do you mean the button where you click to open then menu or the menu itself ?
The button can be sized :
the default min-width css value is 120px but can be overwritten 
thanks to the option "minWidth" (as well as with the option maxWidth")

You may also change directly the style of the button 

document.querySelector("#demo-multiple button").style.minWidth="180px";
"180px"

document.querySelector("#demo-multiple button").style.width="300px";document.querySelector("#demo-multiple button").style.width="300px";

or even the color : 
document.querySelector("#demo-multiple button").style.setProperty("background-color", "lightblue ", "important");

**Comment by PhilippeMarcMeyer** [comment]
precision : "demo-multiple" is the id of the parent div of the select
You can have it directly without knowing the parent div of the select
ex with select id = "brandsMulti"

**document.querySelector("#brandsMulti").parentNode.querySelector("button").style.setProperty("background-color", "pink", "important");**

=> I will modify the vanilla select box in order to simplify access using the id of the original select  !!!

**Comment by danicarla** [comment]
Sorry.. I believe I did not explain correctly :(
In my code I have this
`Select 1:
<select d="example1" multiple size="2" style="width:290px;">
    <option value="1">1</option>
    <option value="2">2</option>
</select>
Select 2:
<select d="example2" multiple size="2" style="width:195px;">
    <option value="3">3</option>
    <option value="4">4</option>
</select>`

It is not a responsive site and the sizes were defined directly in the fields.

If setting a minimum or maximum size does not solve my problem, I need to define the size directly in the select field

**Comment by PhilippeMarcMeyer** [comment]
The select was originally used as a data repository for the
vanillaSelectBox in and out. It is as you know, completely different from
the VSB dropdown . I could  of course make a new version and retrieve the
style properties of the select tag and transfer them to the drop down. But
I need to protect some style attributes otherwise it would not function
properly. Meanwhile you can use the tips I gave in my previous answer :
they work.

**Comment by danicarla** [comment]
I made some changes in CSS and now it works
Thanks for your help :)
